#服务器端口
server:
  port: 8080
#多环境配置
spring:
  profiles:
    active: @env@
#mybatis配置
mybatis:
  mapper-locations:
    - classpath*:sqlmap/mysql/*Mapper.xml
    - classpath*:sqlmap/CommonRoadMapper.xml
  check-config-location: true
  type-aliases-package: com.bear.spring.boot.web.mapper
#配置分页插件
pagehelper:
  autoDialect: true
  closeConn: false
  reasonable: true